services:
  postgres:
    image: postgres:16-alpine
    container_name: asset_manager_postgres
    environment:
      POSTGRES_USER: asset_manager_db     # 修正
      POSTGRES_PASSWORD: password
      POSTGRES_DB: asset_manager_db       # 修正
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: